# Generated by Django 5.2 on 2025-05-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="nazwisko"),
                ),
                ("about", models.TextField(blank=True, verbose_name="o reżyserze")),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="", verbose_name="zdjęcie"),
                ),
            ],
            options={
                "verbose_name": "reżyser",
                "verbose_name_plural": "reżyserzy",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["title"],
                "verbose_name": "film",
                "verbose_name_plural": "filmy",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_at",
            field=models.DateField(verbose_name="data premiery"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="short_description",
            field=models.TextField(verbose_name="opis"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100, verbose_name="tytuł"),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.director",
                verbose_name="reżyser",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=250, verbose_name="autor recenzji"),
                ),
                ("content", models.TextField(verbose_name="treść recenzji")),
                ("is_recommended", models.BooleanField(verbose_name="polecam innym")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="recenzja filmu",
                    ),
                ),
            ],
            options={
                "verbose_name": "recenzja",
                "verbose_name_plural": "recenzje",
            },
        ),
    ]
