# Generated by Django 5.2 on 2025-05-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_director_alter_movie_options_remove_movie_rating_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
