# Generated by Django 5.2 on 2025-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_delete_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="short_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
