# Generated by Django 5.2 on 2025-05-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_options_alter_movie_director_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["title"],
                "verbose_name": "film",
                "verbose_name_plural": "filmy",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.director",
                verbose_name="reżyser",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_at",
            field=models.DateField(verbose_name="data premiery"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="short_description",
            field=models.TextField(verbose_name="opis"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100, verbose_name="tytuł"),
        ),
    ]
